
// Classic display of the sequence

var Sequence = require("sequence-viewer");
var seq1 = new Sequence('MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRREAEDLQVGQVELGGGPGAGSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCNMALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRREAEDLQVGQVELGGGPGAGSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCNMALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRREAEDLQVGQVELGGGPGAGSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCNMALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRREAEDLQVGQVELGGGPGAGSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCNMALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRREAEDLQVGQVELGGGPGAGSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCN');
// You can add some rendering options
seq1.render('#seqView1', {
    'showLineNumbers': true,
    'wrapAminoAcids': true,
    'charsPerLine': 60,
    'toolbar': true,
    'search': true,
    'title': "Protein Sequence"
});
seq1.onMouseSelection(function(elem){
        console.log(elem.detail);
    }
);
seq1.onSubpartSelected(function(elem){
        console.log(elem.detail);
    }
);
//@biojs-instance=seq1
seq1.onAll(function(name,data){
    console.log(arguments);
});
